# Generated by Django 3.1.7 on 2021-03-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210318_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.studentgenre'),
        ),
    ]
