# Generated by Django 3.1.7 on 2021-03-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.major'),
        ),
    ]
