# Generated by Django 3.1.7 on 2021-05-03 18:45

from django.db import migrations, models
import django.db.models.deletion


def seed_database(apps, schema_editor):
    profession = apps.get_model('dashboard', 'Profession')
    profession(name='Matematico').save()
    profession(name='Fisico').save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customuser_cui'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(seed_database),
        migrations.RemoveField(
            model_name='customuser',
            name='major',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.studentgenre'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.profession'),
        ),
    ]
