# Generated by Django 3.1.7 on 2021-05-04 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210503_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
